SELECT LAST_NAME || ' ' || FIRST_NAME || ' ' || MIDDLE_NAME AS FULLNAME, VACCINATIONS, PROBES, REFUSALS, CREATE_DATE
FROM (SELECT SUM(PROBES) AS PROBES, SUM(VACCINATIONS) AS VACCINATIONS, SUM(REFUSALS) AS REFUSALS, SUM(PROBES) + SUM(VACCINATIONS) + SUM(REFUSALS) AS SUM, USER_ID, CREATE_DATE
      FROM (
               SELECT COUNT(*) AS PROBES, 0 AS VACCINATIONS, 0 AS REFUSALS, P.APPLY_USER_ID AS USER_ID, P.CREATED_AT AS CREATE_DATE
               FROM VACCINATION.PROBES P
               WHERE P.SOURCE = 'Tablet'
               GROUP BY P.APPLY_USER_ID, P.CREATED_AT

               UNION

               SELECT 0 AS PROBES, COUNT(*) AS VACCINATIONS, 0 AS REFUSALS, V.APPLY_USER_ID AS USER_ID, V.CREATED_AT AS CREATE_DATE
               FROM VACCINATION.VACCINATIONS V
               WHERE V.SOURCE = 'Tablet'
               GROUP BY V.APPLY_USER_ID, V.CREATED_AT

               UNION

               SELECT 0 AS PROBES, 0 AS VACCINATIONS, COUNT(*) AS REFUSALS, R.USER_ID AS USER_ID, R.CREATED_AT AS CREATE_DATE
               FROM VACCINATION.REFUSALS R
               WHERE R.SOURCE = 'Tablet'
               GROUP BY R.USER_ID, R.CREATED_AT) SUB_INNER
      WHERE CREATE_DATE BETWEEN TO_DATE('01.01.1990', 'DD.MM.YYYY') AND TO_DATE('01.06.2100', 'DD.MM.YYYY')
      GROUP BY USER_ID, CREATE_DATE) SUB_OUTER
         LEFT OUTER JOIN VACCINATION.USERS U ON SUB_OUTER.USER_ID = U.ID
ORDER BY SUM DESC
